$ErrorActionPreference = "Stop"

function Find-ProjectRoot {
    $dir = (Get-Location).Path

    while ($true) {
        if (Test-Path (Join-Path $dir "Cargo.toml")) {
            return $dir
        }

        $parent = Split-Path $dir -Parent
        if ($parent -eq $dir) {
            throw "找不到项目根目录：请在 Cargo 项目目录内运行"
        }

        $dir = $parent
    }
}

function Escape-TomlString {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Value
    )

    return $Value.Replace("\", "\\").Replace('"', '\"')
}

$projectRoot = Find-ProjectRoot
$exportEsp = Join-Path $Env:USERPROFILE "export-esp.ps1"

if (!(Test-Path $exportEsp)) {
    throw "找不到 $exportEsp，请先运行 espup install/update"
}

# 关键：直接执行 espup 生成的脚本，拿到真实环境
. $exportEsp

if (-not $Env:LIBCLANG_PATH) {
    throw "执行 export-esp.ps1 后没有得到 LIBCLANG_PATH"
}

if (!(Test-Path $Env:LIBCLANG_PATH)) {
    throw "LIBCLANG_PATH 指向的文件不存在：$Env:LIBCLANG_PATH"
}

$cargoDir = Join-Path $projectRoot ".cargo"
$outFile = Join-Path $cargoDir "esp.local.toml"

New-Item -ItemType Directory -Force -Path $cargoDir | Out-Null

$libclang = Escape-TomlString $Env:LIBCLANG_PATH
$pathValue = Escape-TomlString $Env:Path

@"
# Auto-generated by scripts/gen-esp-cargo-env.ps1
# Source: $exportEsp
# Do not commit this file.

[env]
LIBCLANG_PATH = { value = "$libclang", force = true }
Path = { value = "$pathValue", force = true }
"@ | Set-Content -Path $outFile -Encoding UTF8

Write-Host "Generated: $outFile"
Write-Host "LIBCLANG_PATH=$Env:LIBCLANG_PATH"
Write-Host "Path first entries:"
($Env:Path -split ';' | Select-Object -First 8) | ForEach-Object {
    Write-Host "  $_"
}